config/routes.rb
Rails.application.routes.draw do
  resources :things
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/thing.rb
class Thing < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  # GET /things
  def index
    @things = Thing.all
  end

  # GET /things/1
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  def create
    @thing = Thing.new(thing_params)

    if @thing.save
      redirect_to @thing, notice: 'Thing was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /things/1
  def update
    if @thing.update(thing_params)
      redirect_to @thing, notice: 'Thing was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /things/1
  def destroy
    @thing.destroy
    redirect_to things_url, notice: 'Thing was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def thing_params
      params.require(:thing).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeneratorHookInvestigation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/things/_form.html.slim
= form_for @thing do |f|
  - if @thing.errors.any?
    #error_explanation
      h2 = "#{pluralize(@thing.errors.count, "error")} prohibited this thing from being saved:"
      ul
        - @thing.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/things/edit.html.slim
h1 Editing thing

== render 'form'

=> link_to 'Show', @thing
'|
=< link_to 'Back', things_path

app/views/things/index.html.slim
h1 Listing things

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @things.each do |thing|
      tr
        td = thing.name
        td = link_to 'Show', thing
        td = link_to 'Edit', edit_thing_path(thing)
        td = link_to 'Destroy', thing, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Thing', new_thing_path

app/views/things/new.html.slim
h1 New thing

== render 'form'

= link_to 'Back', things_path

app/views/things/show.html.slim
p#notice = notice

p
  strong Name:
  = @thing.name

=> link_to 'Edit', edit_thing_path(@thing)
'|
=< link_to 'Back', things_path